parameters:
    dlin.array_conversion_bundle.metadata_factory.class: Dlin\Bundle\ArrayConversionBundle\Metadata\MetadataFactory
    dlin.array_conversion_bundle.metadata.annotation_driver.class: Dlin\Bundle\ArrayConversionBundle\Metadata\Driver\AnnotationDriver
    dlin.array_conversion_bundle.metadata.cache.class: Dlin\Bundle\ArrayConversionBundle\Metadata\Cache\FileCache

services:
    dlin.array_conversion_bundle.metadata.annotation_driver:
      class: %dlin.array_conversion_bundle.metadata.annotation_driver.class%
      arguments: [@annotation_reader]

    dlin.array_conversion_bundle.metadata_factory:
      class: %dlin.array_conversion_bundle.metadata_factory.class%
      arguments: [@dlin.array_conversion_bundle.metadata.annotation_driver, Metadata\ClassHierarchyMetadata, %kernel.debug%]
      calls:
        - [setCache, ["@dlin.array_converter.metadata.cache"]]

    dlin.array_converter:
      class: Dlin\Bundle\ArrayConversionBundle\Service\ArrayConverter
      arguments: [@dlin.array_conversion_bundle.metadata_factory]

    dlin.array_converter.metadata.cache:
      class: %dlin.array_conversion_bundle.metadata.cache.class%
      arguments: [/]
